version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: PWD4toor
      MYSQL_DATABASE: test

  web:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        npm run build
        npm run typeorm:run
        npm run start
    ports:
      - "3001:3000"
    depends_on:
      - db
